package:
  name: readline
  version: 6.3

source:
  fn: readline-6.3.tar.gz
  url: ftp://ftp.cwru.edu/pub/bash/readline-6.3.tar.gz


about:
  home: http://cnswww.cns.cwru.edu/php/chet/readline/rltop.html
  license: GPL 3

build:
  number: 4
  detect_binary_files_with_prefix: true

requirements:
  build:
    - ncurses >=5.9
  run:
    - ncurses >=5.9

# vim:set ts=8 sw=2 sts=2 tw=78 et:
