package:
  name: collection
  version: '2015_03'
# https://github.com/ericdill/conda-prescriptions/blob/add-dp-v0.2.2/beamline-environments/proposed-deployment-strategy.rst


build:
  number: 1

requirements:
  run:
    - analysis
    - bluesky
    - ophyd
