package:
  name: analysis
  version: '2015_03'

build:
  number: 1

requirements:
  run:
    - python
    - jupyter
    - ipywidgets
    - pymongo <3.0
    - databroker
    - channelarchiver
    - lmfit
    - matplotlib >=1.5.0rc1
    - openpyxl
    - scikit-xray
    - xray-vision
    - album
